# .travis.yml
#
# parrot

language: rust
rust:
  - stable
  - nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
branches:
  only:
    - substratev2
matrix:
  allow_failures:
    - rust: nightly
