[workspace]
members = [
    'node',
    'pallets/template',
    'pallets/prc20',
    'pallets/multi_transfer',
    'pallets/delegation',
    'pallets/burn',
    'runtime',
]
[profile.release]
panic = 'unwind'
