version: "3.2"

services:
  dev:
    container_name: parrot
    image: parity/ci-linux:production
    working_dir: /var/www/parrot
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/parrot/.cargo
    volumes:
      - .:/var/www/parrot
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/parrot --dev --ws-external"
